# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Gallery Guide
email: info@thegalleryguide.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Github organisation page for The Gallery Guide
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://galleryguide.github.io/" # the base hostname & protocol for your site
twitter_username: thegalleryguide
github_username:  GalleryGuide

# Build settings
markdown: kramdown
